name: Build

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}/builder
        tags: |
          type=raw,value=latest
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    - name: Cache source archive
      uses: actions/cache@v3
      with:
        path: |
          cache
          prefix
          wasm-build
        key: archive-${{ github.sha }}
        restore-keys: |
          archive-
    - name: Prepare containers
      uses: docker/build-push-action@v4
      id: build-container
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        load: true
    - name: Build
      run: |
        # docker run --name builder --rm -v "$(pwd)/cache:/tmp/cache" -v "$(pwd)/scripts:/scripts" -v "$(pwd)/.:/home/emscripten/src" -u emscripten -e PREFIX=/home/emscripten/src/prefix ghcr.io/${{ github.repository }}/builder:latest /scripts/ci.sh
        docker run --name builder --rm -v "$(pwd)/cache:/tmp/cache" -v "$(pwd)/output:/tmp/output" -u emscripten ghcr.io/${{ github.repository }}/builder:latest /bin/bash -c "cp -r /home/emscripten/src/wasm-install /tmp/output; cp -r cache /tmp/cache"
    - uses: actions/upload-artifact@v3
      with:
        name: wasm
        path: output
