name: Build

on:
  push:
    paths-ignore:
      - "*.md"
      - ".*"
      - "*config*"
      - "!.github"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "19"
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache source archive
      uses: actions/cache@v3
      with:
        path: |
          cache
          prefix
          wasm-build
        key: archive-${{ github.sha }}
        restore-keys: |
          archive-
    - name: Change cache directory permission
      run: chmod 777 cache
    - uses: docker/bake-action@v3
      with:
        load: true
        files: docker-compose.yml
    - name: Build
      run: docker compose up
    - name: Create package tarball
      run: corepack yarn pack --install-if-needed -o libxmlwasm.tgz
    - name: Upload package tarball
      uses: actions/upload-artifact@v3
      with:
        name: libxmlwasm.tgz
        path: libxmlwasm.tgz
