name: Publish Package to npmjs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: libxmlwasm.tgz
          path: libxmlwasm.tgz
      - run: ls . */
