name: Publish Package to npmjs

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Download artifact
        run: |
          runid=$(gh run list -w build.yml -s success -c $GITHUB_SHA --json databaseId -q ".[0].databaseId")
          gh run download $runid -n libxmlwasm.tgz
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Unpack artifact
        run: |
          tar axf libxmlwasm.tgz
          mv package/dist .
          rm -rf package libxmlwasm.tgz
      - run: ls . */

      - name: Publish to npm
        run: corepack yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
